# Generated by Django 6.0.3 on 2026-04-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_session_difficulty_mixed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_number']},
        ),
    ]
